name: Trigger Hello Workflow

on:
  workflow_dispatch: # Triggered manually

jobs:
  trigger:
    runs-on: ubuntu-latest

    steps:
    - name: Trigger Hello Workflow
      uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.REPO_TOKEN }}
        script: |
          const response = await github.repos.createDispatchEvent({
            owner: 'tmtsmrsl',
            repo: 'test_repo_1',
            event_type: 'hello'
          });
          console.log(response.data);